name: Rust Server with SSH Access

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-and-run-rust-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt-get update || true
        sudo apt-get install -y lib32gcc-s1 openssh-server || { echo "Failed to install packages"; exit 1; }

    - name: Start SSH service
      run: |
        sudo mkdir -p /var/run/sshd
        sudo chmod 0755 /var/run/sshd
        sudo /usr/sbin/sshd

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Start ngrok for SSH tunneling
      run: |
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok tcp 22 --region us &

    - name: Wait for ngrok to start
      run: |
        sleep 5  # Increased from 1 second to ensure ngrok has started

    - name: Display ngrok tunnel info
      run: |
        curl --silent --show-error http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://.*'

    - name: Download SteamCMD
      run: |
        mkdir steamcmd
        cd steamcmd
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz

    - name: Install Rust Server
      run: |
        cd steamcmd
        ./steamcmd.sh +login anonymous +force_install_dir ../rust +app_update 258550 validate +quit

    - name: Run Rust Server
      run: |
        cd rust
        nohup ./RustDedicated -batchmode +server.port 28015 +server.hostname "Your Server Name" +server.maxplayers 100 +server.worldsize 4000 +server.seed 12345 +server.identity "server1" +rcon.port 28016 +rcon.password "YourRCONPassword" &
      env:
        LD_LIBRARY_PATH: /home/runner/work/your-repo-name/your-repo-name/rust/Linux64

    - name: Keep server running for testing
      run: |
        sleep 21600  # Keep running for 1 hour (3600 seconds); adjust as needed
