name: Run Rust Server Continuously

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # каждые 30 минут

jobs:
  run-rust-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32gcc1

    - name: Download SteamCMD
      run: |
        mkdir steamcmd
        cd steamcmd
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz

    - name: Install Rust Server
      run: |
        ./steamcmd/steamcmd.sh +login anonymous +force_install_dir ./rust +app_update 258550 validate +quit

    - name: Run Rust Server
      run: |
        cd rust
        ./RustDedicated -batchmode +server.port 28015 +server.hostname "Your Server Name" +server.maxplayers 100 +server.worldsize 4000 +server.seed 12345 +server.identity "server1" +rcon.port 28016 +rcon.password "YourRCONPassword"
      env:
        LD_LIBRARY_PATH: /home/runner/work/your-repo-name/your-repo-name/rust/linux64

    - name: Keep server running
      run: |
        sleep 99999 # 30 минут, это максимальное время, которое позволяет GitHub Actions для одного запуска

    - name: Trigger another run
      if: always()
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Run Rust Server Continuously
        token: ${{ secrets.PAT }}  # Пат токен с правами на запуск workflow
