name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/iliavik1/hu/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/cwbwdo2n3tt8rbqmugc6h/show.bat?rlkey=41m0ds12mg6e28giib3zqlf6w&dl=1" -OutFile "show.bat"
          cmd /c show.bat

      - name: Time Counter
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/iliavik1/hu/main/time.py" -OutFile "time.py"
          python time.py
