name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the required Python version

      - name: Install Python Dependencies
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found; skipping dependency installation."
          }

      - name: Downloading & Installing Essentials
        run: |
          if (Test-Path .\Downloads.bat) {
            .\Downloads.bat
          } else {
            Write-Error "Downloads.bat not found in the repository."
          }

      - name: Log In To AnyDesk
        run: |
          if (Test-Path .\show.bat) {
            .\show.bat
          } else {
            Write-Error "show.bat not found in the repository."
          }

      - name: Time Counter
        run: |
          if (Test-Path .\time.py) {
            python .\time.py
          } else {
            Write-Error "time.py not found in the repository."
          }
