name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/iliavik1/hu/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/iliavik1/hu/main/time.py" -OutFile "time.py"
          python time.py
